"use strict";
var mensagem = (nome) => console.log("Bem vindo: " + nome);
mensagem("Paulo");
let texto = "Typescript 3.0.3";
let numeroDia = 26;
let estudoAngular = true;
let listaLetras = ['a', 'b', 'c', 'd', 'e'];
let listaNumeros = [1, 1.1, 2, 3, 4.5];
let listaLetras2 = ['a', 'b', 'c', 'd', 'e'];
let listaNumeros2 = [1, 1.1, 2, 3, 4.5];
